// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SrcComponentsDatatable: typeof import('./src/components/Datatable.vue')['default']
    SrcComponentsEvent: typeof import('./src/components/Event.vue')['default']
    SrcComponentsPreview: typeof import('./src/components/Preview.vue')['default']
    SrcComponentsTimetable: typeof import('./src/components/Timetable.vue')['default']
    SrcEmbeddedMain: typeof import('./src/embedded/Main.vue')['default']
  }
}

export { }
