// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Datatable: typeof import('./src/components/Datatable.vue')['default']
    Event: typeof import('./src/components/Event.vue')['default']
    'Menu.Timetable': typeof import('./src/components/Menu.Timetable.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    Timetable: typeof import('./src/components/Timetable.vue')['default']
  }
}

export { }
