// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Node_modulesVueDatasetPlaygroundApp: typeof import('./node_modules/vue-dataset/playground/App.vue')['default']
    Node_modulesVueDatasetPlaygroundComponentsHelloWorld: typeof import('./node_modules/vue-dataset/playground/components/HelloWorld.vue')['default']
    Node_modulesVueDatasetPlaygroundLayoutsDefaultDefault: typeof import('./node_modules/vue-dataset/playground/layouts/default/Default.vue')['default']
    Node_modulesVueDatasetPlaygroundLayoutsDefaultDefaultFooter: typeof import('./node_modules/vue-dataset/playground/layouts/default/DefaultFooter.vue')['default']
    Node_modulesVueDatasetPlaygroundLayoutsDefaultDefaultNav: typeof import('./node_modules/vue-dataset/playground/layouts/default/DefaultNav.vue')['default']
    Node_modulesVueDatasetPlaygroundViewsExample1: typeof import('./node_modules/vue-dataset/playground/views/Example1.vue')['default']
    Node_modulesVueDatasetPlaygroundViewsExample2: typeof import('./node_modules/vue-dataset/playground/views/Example2.vue')['default']
    Node_modulesVueDatasetSrcDataset: typeof import('./node_modules/vue-dataset/src/Dataset.vue')['default']
    Node_modulesVueDatasetSrcDatasetInfo: typeof import('./node_modules/vue-dataset/src/DatasetInfo.vue')['default']
    Node_modulesVueDatasetSrcDatasetItem: typeof import('./node_modules/vue-dataset/src/DatasetItem.vue')['default']
    Node_modulesVueDatasetSrcDatasetPager: typeof import('./node_modules/vue-dataset/src/DatasetPager.vue')['default']
    Node_modulesVueDatasetSrcDatasetSearch: typeof import('./node_modules/vue-dataset/src/DatasetSearch.vue')['default']
    Node_modulesVueDatasetSrcDatasetShow: typeof import('./node_modules/vue-dataset/src/DatasetShow.vue')['default']
    Node_modulesVueToastificationSrcComponentsIconsVtErrorIcon: typeof import('./node_modules/vue-toastification/src/components/icons/VtErrorIcon.vue')['default']
    Node_modulesVueToastificationSrcComponentsIconsVtInfoIcon: typeof import('./node_modules/vue-toastification/src/components/icons/VtInfoIcon.vue')['default']
    Node_modulesVueToastificationSrcComponentsIconsVtSuccessIcon: typeof import('./node_modules/vue-toastification/src/components/icons/VtSuccessIcon.vue')['default']
    Node_modulesVueToastificationSrcComponentsIconsVtWarningIcon: typeof import('./node_modules/vue-toastification/src/components/icons/VtWarningIcon.vue')['default']
    Node_modulesVueToastificationSrcComponentsVtCloseButton: typeof import('./node_modules/vue-toastification/src/components/VtCloseButton.vue')['default']
    Node_modulesVueToastificationSrcComponentsVtIcon: typeof import('./node_modules/vue-toastification/src/components/VtIcon.vue')['default']
    Node_modulesVueToastificationSrcComponentsVtProgressBar: typeof import('./node_modules/vue-toastification/src/components/VtProgressBar.vue')['default']
    Node_modulesVueToastificationSrcComponentsVtToast: typeof import('./node_modules/vue-toastification/src/components/VtToast.vue')['default']
    Node_modulesVueToastificationSrcComponentsVtToastContainer: typeof import('./node_modules/vue-toastification/src/components/VtToastContainer.vue')['default']
    Node_modulesVueToastificationSrcComponentsVtTransition: typeof import('./node_modules/vue-toastification/src/components/VtTransition.vue')['default']
    SrcComponentsDatatable: typeof import('./src/components/Datatable.vue')['default']
    SrcComponentsEvent: typeof import('./src/components/Event.vue')['default']
    SrcComponentsPreview: typeof import('./src/components/Preview.vue')['default']
    SrcComponentsSelect: typeof import('./src/components/Select.vue')['default']
    SrcComponentsTimetable: typeof import('./src/components/Timetable.vue')['default']
    SrcEmbeddedMain: typeof import('./src/embedded/Main.vue')['default']
  }
}

export { }
