name: Distribute

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      if: startsWith(github.event.commits[0].message, 'v0.')
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ github.event.commits[0].message }}
    - uses: actions/checkout@v1
    - name: action-yarn
      uses: comchangs/action-yarn@v0.1-beta
    - name: yarn install and build
      run: |
        yarn install
        yarn run build
      env:
       CI: true
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          package.json
          ${{ github.event.commits[0].message }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
