name: Distribute


on: [push]
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
#     - uses: actions/checkout@v1
#     - name: action-yarn
#       uses: comchangs/action-yarn@v0.1-beta
#     - name: yarn install and build
#       run: |
#         yarn install
#         yarn run build
#       env:
#         CI: true
    - name: Package Release
      uses: lubusIN/actions/archive@master
      env:
        ZIP_FILENAME: release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
