name: Distribute


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: action-yarn
      uses: comchangs/action-yarn@v0.1-beta
    - name: yarn install and build
      run: |
        yarn install
        yarn run build
      env:
        CI: true
    - name: Package Release
      uses: thedoctor0/zip-release@master
      with:
        filename: release.zip
        path: /dist
    - name: Release 
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
